### ISSUE TITLE
Build failure on SmartOS (6.2)

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#16]
CI run: https://ci.nodejs.org/job/node-test-commit-smartos/10884/nodes=smartos15-64/console

Error:
```
  touch /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/obj.target/node_dtrace_provider.stamp
dtrace: failed to compile script src/v8ustack.d: line 293: failed to resolve V8DBG_FRAMETYPE_ENTRYCONSTRUCTFRAME: Unknown variable name
node_dtrace_ustack.target.mk:26: recipe for target '/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/obj.target/node/src/node_dtrace_ustack.o' failed
make[2]: *** [/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos15-64/out/Release/obj.target/node/src/node_dtrace_ustack.o] Error 1
```

@nodejs/platform-smartos

**Comment by cjihrig** [comment]
I'll take a look.

**Comment by targos** [comment]
This is still happening. Latest run: https://ci.nodejs.org/job/node-test-commit-smartos/11137/nodes=smartos16-64/console

**Comment by geek** [comment]
Fixed in the latest: https://ci.nodejs.org/job/node-test-commit-smartos/11139/ via https://github.com/nodejs/node/commit/44f5ffebdfae8fc17336328e2fabbe1ed038f38b

**Comment by targos** [comment]
I'm reopening because the build is still failing with this commit and with the same error message: https://ci.nodejs.org/job/node-test-commit-smartos/11145/

**Comment by geek** [comment]
@targos thanks, I'll investigate... looks like a new culprit this time

>failed to resolve V8DBG_FRAMETYPE_ENTRYCONSTRUCTFRAME

**Comment by targos** [comment]
Fixed by https://github.com/nodejs/node/commit/50cc6c71991294d904ff26bfebe2467a5321239d

**Comment by misterdjules** [comment]
@targos Just to make sure we're on the same page, some of the commits that fix the build issue on SmartOS are temporary fixes (like https://github.com/nodejs/node-v8/commit/f6bd6af88f1a35c11ffc36cf13c2881b36598046), and some of them may not have been through a standard review/testing process (like https://github.com/nodejs/node/commit/50cc6c71991294d904ff26bfebe2467a5321239d).

@cjihrig, myself and others have started to take a closer look at fixing the DTrace and post-mortem debugging issues with recent V8 versions, and we should be able to come up with less temporary fixes soon.

**Comment by targos** [comment]
@misterdjules all commits that are on `canary-base` but not on `master` can be considered temporary fixes. This branch only exists to collect fixes that the bot can cherry-pick to this repository for the `canary` updates/tests/nightly.

They will go through a standard review process when a PR is opened in the node repository to update V8 on `master` or they will be removed once the changes are upstreamed to V8 when applicable.
